apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealedsecrets-operator
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: 'cluster'
  template:
    metadata:
      name: '{{.name}}-sealedsecrets-operator'
    spec:
      project: default
      source:
        path: operators/sealedsecrets
        repoURL: 'https://github.com/too-common-name/veeam-demo.git'
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{.server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true