{{- if eq .Values.acm.enabled true }}
    {{- range .Values.subscriptions -}}
      {{- if eq .name "advanced-cluster-management" -}}
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
    name: multiclusterhub
    namespace: {{ .namespace }}
    annotations:
        argocd.argoproj.io/sync-wave: "3"
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: dr-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: dr-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    cloud: BareMetal
    vendor: OpenShift
spec:
  hubAcceptsClient: true
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-gitops
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default-gitops-placement
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: default-gitops-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: default-gitops-placement
      {{- end -}}
    {{- end -}}
{{- end }}