{{- if eq .Values.acm.enabled true }}
    {{- range .Values.subscriptions -}}
      {{- if eq .name "advanced-cluster-management" -}}
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
    name: multiclusterhub
    namespace: {{ .namespace }}
    annotations:
        argocd.argoproj.io/sync-wave: "3"
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: dr-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    cloud: auto-detect
    vendor: auto-detect
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: dr-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: dr-cluster
spec:
  clusterName: dr-cluster
  clusterNamespace: dr-cluster
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  version: 2.3.0
      {{- end -}}
    {{- end -}}
{{- end }}