{{- if .Values.kasten.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k10-eula-info
  namespace: kasten-io
data:
  accepted: "true"
  company: '{{ .Values.kasten.company }}'
  email: '{{ .Values.kasten.email }}'
---
apiVersion: apik10.kasten.io/v1alpha1
kind: K10
metadata:
  annotations:
    helm.sdk.operatorframework.io/reconcile-period: 2m
    helm.sdk.operatorframework.io/rollback-force: 'false'
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: k10
  namespace: kasten-io
spec:
  auth:
    basicAuth:
      enabled: false
      htpasswd: ''
      secretName: ''
    tokenAuth:
      enabled: true
  global:
    persistence:
      catalog:
        size: ''
      storageClass: ''
  metering:
    mode: ''
  route:
    enabled: true
    host: ''
    tls:
      enabled: true
---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: "profile-awss3-kasten"
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      name: "{{ .Values.kasten.bucket_name }}"
      objectStoreType: S3
      region: "{{ .Values.kasten.bucket_region }}"
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: "k10-awss3-kasten-backup-secret"
        namespace: kasten-io
  type: Location
{{- end }}
