{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-demo-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    awsAccessKeyId: AgCECvqzpSI7Jyb95XV/EUGDNiTvju2YTzp0nW3A/oZ6dTTz1iSWd7xi9HbscqRAqPGQGytHHkJLg094ppxlKNXM1PSzDUDmKAoV2hwJb6gwr/9pFlvAD5yHF5dP0vXGHKW+foH7EQaXclRNQl7dmftNb47PlFi4TrmEQbDIYMRGjMQw7wZLm7A/9lvKP17WpQUWpziI5+UwO8kEz6ghqqdYwkseTEmGoGqyXFdUpXI6DqrAta3Kjk0e6sLwgPaY9VX4wy4RuFC5qk5d8LeYRFbFxCJjGf4JzOcqj+z6brgGKhQ1UOHP9bMZ138cigZhT3RKxsC+VVqAaE77yC5EZWV3dTj6oEaVDzFoaR7qDYsAq3gtlXzf00tFuQsQE96EQ+SSvPvDUukJP+jeeJj39aqTNt4y7oJ4jctuWkrXfdYSGRTVZGWHm/d7a6+ncE82TvBHr6hbMsqM8zHvwpKaPOebvqsdyMQ6TWLJHSgoRQH+QtYf4tH903hbgFc1WvW2TCH10f4xVHCDlThPL2wPP4W4Yn0XSB7N2oA4DH7MLoDmEpQcPsBK8pnMqlo4KxVu+ToC0/66ygbRyOCgfwQYAjNwBYngZ2NbjkX2+iyn5WpyAQm0ClLDbdzucQm39bkB8+8T0seBKoJjkWT2sKkSzDt/HTy86GXfa9loWfQdHjJC/BMu3BISc3riep4jS5MTuR/2/omhlpXRhvs/TIq2p0jfiD1YxYU=
    awsSecretAccessKey: AgA95jt60MRMGvmw/gDzFWmT1N3otp2UblziyHO3WU5aCPwhzRh1yfaBTTL9NZOeZwJTS4I3DSyKwIoQrHWC2nWqHcW5VChgq/ixkMZD2khb1pP9RaQEOVFfEAFPHKanrEMjGAn0ZJI9lLN6io8E4mK8nfw0woUguB8siSjM0CvD5HTXwJo4ikUMm+sJrbQbhEisG7aCLHtxJ1Pd+KJbSAQ1YPO7QXyU8l+UU0rccUpYtTaWof2IGiW7Aa1FCufqdI763e+9Ci6UkqdCHyQCqk6lTB6hr/bwGhCViQl10HxtpfESJT6lt46L++4g5eZ4BcV4eZ373AwFkmUoDfp/HZP1LFt2xq4qnfkTf7I2wVAr1fyoEKHriRXqNRyKhlsDQaYbxg6HWulKhyDFFx4hKocn8/d0Zlt9VNw+B9XuIjwiNxYWKkr/dxBT4O3W3NpUxL7yfmSYAJlyD3bNfmWdeB+X0A4etntm9E8tU+ccoi4RXWBaGgM/KTrtCcR346+cWl4ymgPF2hLlBFs+ageeyedX/0P0Twa4o3ugTg5DX0ZctCYOq6W9qL0rv4tYkesHgs66Kfj/KnAk4oVTPZmap2CNMGLnz+4HJzvOT9afxyeFVSWykCUbAxBo2N6exKDYb3csFbLslXvlh1j/2gMWHj0VxpAP5C0hILQTLRma0R1//jtN03DiSUa1S/r6UNfHOR9BYAY7yT50N4R9Lc3Aph//jQhUZxijBMWHzaqnd+OZYWPl3Ep++QJd8Q==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: k10-awss3-demo-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
