{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-webinar-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgCXUfZ2NbKmxUzPxQaUkOYb+CK8rLPVl5rrNczs+F0k4iStjgeVUNf2WxwUUY9BtYZU+4KUJ5T+x96bwpuWz/WOf6dKCKU3bzkD5uLiVelGbDZCtWBAMNNWjWRjk14hD+SdjFXUI4Y7VPaJ2xfCWQKZpaJIk6PqG12zTLW4TNKOITrQBa2OZ8XaCg7AWiFnrx7Pi35qkSvfKy5nKnZNcLuRRsg7PTYd3uxFVZVNuGNX999m5xN0RPcI4PgBARwAnhikGNZlSZRVi+gMUO4zH/HTWcpvPrW4AR0LfVkL8bZxR+zPk5K6lBosl0QpVYrBseFSi96J8RADWG56JGj9pHdfpbmWAC6SZnRK0WckTjcNAnxR67D2jlUGULAyC2Tzr2Vn9BuiPmVdPyXeM9mxP9XmPiG/0GCJVaxABatJOdmujBoWVG54xME6rxgPQmqEKxXQt2elwvS6bTJTKzxn4GpzjTyRMPavWuzsqWnoUq11vvfjWeJkgFlkfUjwHRIlOyDD6etnSL2LwDrQg/nF1vSD74rbovTELrZ+aKWEETTPyVR2lYNCMleBlKXy+zVqgWGYlcFoJR/eLA5/xebVuXGe1g4hJ5s7/JGDINUUxLsSQWckTfuQHTL7kqkOxCr+L6XQqUaU1IUWih5pnwQ3oCq2u8GaxtZZj+/Nw4VIEX8HmMQCVooDZtp5ahx9wF/NDL+9ShPblnKK4rkaB/xTtMk=
    aws_secret_access_key: AgBX2hq5TU+SCWLzsekpKmLvXDrApIxak7SVZGHXLtfKYzG8XTtWfaqAAFAtGv/JBDPvPcbbNKk5zFyQr17t8FlxzAQuEhEFyEWAA0uRyFAyaQzabfixer7snG8aY4uQjZVPQL9GV/NANZBNS90lvZxtKORHaWf9kA5q2iNJpJIqSVAycbaOO6+CqO222BsWHwgIiNtVFTxw8KX3ZQj7h1OrFue+pZuhTd7Q86PMhRgCifjtO6dlybWwGccAfbainIL7XVNmdylF5J/H3HeSq4ifU5omTQ3DmdJCaYdDghavA74uFr6kt5XiI0KQB/zQwXVl9C5fNKhFFWhfvoj3hdRS1zBPCOTANuNvcLWWJSceggIxEvVHqrIhKOzPipvVNQvlLYIwloJXeHN5Sj4u7E5UNovoRUYt21Gf0uE/xkYM+CGbz5HhcFtfEJ1mUOVM3LTdwd7MQjrGF/zt102Uuy/UNw2cz38Ot7ki8rK/bYEd0B2E56+MB+GyFwlzs7FJeayfsEV6OSDSn8Qjl7tEpaMnk3MvotlG7oFA2aP069hdzC/vUFQrzeJEpwJ5chvXijiQn+wW/6NCQFRJyuB0B1r+B+5oGALlh6VaEcDl95l/ISdQSeRg8q2meylHbjMEfi/R6aAz9NHiK5Ah7nlT+Vsn0kGj35eqUuojpudE5XPmaVm1ebd8HTIGgeG12+YzaW9EJ64gix9Kfs5uBbsCQz09Zn5/lGAXFRw35IVpURE=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: k10-awss3-webinar-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
