{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgB7Cw8zbl3a2ZPe1xK7LOPKRnxUD8ZT79A9YAEnlmZa3k7vGAM+YGcBdq6PXARyAKzjOV3uHrIb42TbsPfPPTX+/m180+ApImCkC43AHXM4B/tQHoNSVsYawTJWE+/cYrmivvXrJXdd+rq7a72oSvxjDEiWalHeBm2PBrMcHvKomNAYhQxgAzYu3s95XNqoiWOfToKlde1uX2KOUfP8C0ezWvnT8UWwas1u+/WWXBJ3M/y0aP55c/PInp9EGlPbWaYqkpmwY9PIgSmgK1H1DeQbEAU1/2GRep2/fQfXha4BZdw3kccie6Pi9ldgcXClyNzeA3Z9AxT9yD7VoQ87a0Y+/+k9VFQTvsazxazc9omvRZa5rMIG2r/3yh8Bz6zuM7GliFLvUEMxmxGeicpJIYsn0Tuns6XNLNF3jcFAkAyfkQZbkuXDAXLJYeoDNREdN5M1NK8zaZLSpF9SyLOe90el4Xd3j44JST4t+IWtbhJ86i/e5HKyGsaJMTXAWXJTy3XGX0f4wAA4eduZhsE+ZBG0XHuTiyi3CBETGkjaIbeOXS0FW+YhNJywqh/+/tKnH6Pxwy4K+BP/D0JCciivXtNG5dGjF3v2wfRlB9wiFlMcqDwTkbmEdIi1FwGHlEOvl5Cx6JJivhkb46d5tZVt2ht0w9N8KmUSy6dI1pq2VBe6Qhmp8WpAE0ZVJvfZAJlOLTpYzOgyYJcCu43ohd0vJ6Q=
    aws_secret_access_key: AgBg7Z5q5muGbY8HsUeS9PfTMw2nEKavtfmm6yI3o4lGWUD+URRYZi3g091leAIUZnG4zflVw1P3+RdBLJhtkbnbq8+9sIP8dM9I3FbyiuS1KH7HvqhzJHT70eYLFz7z6LQ5KZ3Kre6bVgwnOT3QQTZKkb/8WkMHftGxIfFeOu2pXHmYNFRz+TnKwjIiV105D2E9Ycqt03gvK2za+Njj83LstIkNmcGsX0dZsTmrV4S4crH2PiUWYmVgOauFfH4CFCVaI0KoaZEP3RIfQCNQkYkU9EJRBhiwhcKQukvoOasEhhAUivEh53YaPAJjL2IbQPUR6VfN85zmxtifY74af8OqROf8vwT5L67vlnOk+6H0E2hSGkvboeGj6CInvWevDfFcgQ8Z78O+eI8DPINPR3ugnLi1BZYfgP6K1UGoRfa5rcvUXw652QqytRrpFOgzgd4O2ZWe3/YmzkKSejfbJD1PXjLcwBghL2gN3QJE0qdffqgQhCbE0DGJMzsBNPAsUcecU2wEP2PK+d19rX7Y/0wOKKgrjgSBlklmPGtF9nKWyv2fWpngOR1zaX8gvs5u1gSvP6ospPbkrncxqGUbyVmDsX3iTetg3Kyq1TdNzrAqf2z44lBZ3pSn7rpUrrd1xad0oZGY+AUWYcUcrOURttMLBqhFNct6v/I0kVZlBYHXELEc8lk/Vggjv2RO4S7OCR0onbrjq5jO7bHRGkQnJ4eXKftuqUrPo7LbHgbQZSE=
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
