{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgCgUZbS6BKroyOx+/8dqw3urNr1UpkvvMDuccwY+X47Bokxq6KC5CckmkLDcSWz3gzBgehYjZnd6wAY5Cmx+B/1nw71zQSpzP36sJNIIhSQv+i4NvBEAwgUR5dfJsV2APGRJWOW9XRs8h4zbWuNuY8qYYxtBXyBPjtg4JG9T2ezCLtoHfOkhyPW2otVqXU1K3YcpSsQiLTbsrQGE2z6ioMESAo6EHXPgH96cTq7/PmN18FbsRFx1zReJckNEDC3uB7gKwCsS/hRet7D9axDUnvIIQncVzo2cqw32D/KqYm48x4E+Ml/RDoeP/qZDndOLqZ+vwAYGDSnUlh6QtW6bSphzam15u/Nv6cb1xIF18T4FgvLux7sLYWgc4rXQ3N1I1JWkpp5LJdcMctxa6cPo7X8Soh3F0jj4DKAdZcX1THA4lrgyl6E4BQJycPifM6TsAGykF2lHgU6p5uNlpOo5G1SJzOHUQH5/rehMJGrFlI8m4HGqk5k8WAkrbu0dKeRKl3774JzmBVQilgew+v70e7pFVQWVzq6v4WZc3eidoA0i9noj2xw8mkJeLI/hLXThS9gT4qjFGdaDhr+hDKGbPYs+aDMclitTIshmtaXPOYoKkCbQueva+DSaSXAJpDTDMMKJ411e03w21wQp1cRsfV8jzb0RCvHi1Ipx5ZyAsizi/NuUTNmLd36EfeRyuuhHyKvn+KW/b1T8txuwJvwraorsy4pAgU=
    aws_secret_access_key: AgAGJE4zd2UAU0TLK7urBYzgIdkoMq/BraXBQPZ3vvnweasjU95ych8+n6v+RKuuvGua05j9+oQnqJhTm3puKqo/2d5Paiv5yfJyzkUyaCIPANEhvuojWp36MhZagJUVQoRelmd6XbyAlRwoSjUsyz4610XbVzR26byuFGBtjkqSlVrUjySm9urNJ/9fdJAwxNh1phdiQy7Bc3zwGkUo/o852dxqhsRIoCDbCn35DDvk3CgCCAOmE/dZhrhNXf45svS58nhmchFwJhmgc6jbbcpJQLwwtKBOD7OyR6p1Bzz4cEUkk/a6MHQMQOdSiKM/NtP5u9pyT2ndddJ++sO6lLCRJByPy0ep/ghciGqgMEKo6IM3SSXtl67Dka2gm+ftwelPfCnH3VHCfOtIJoAslGqSrY7Wkdu+N03WzxSJNYt7eQAVDwBOzKg1X6LrWnfyn38yvHsTXEzFRaJ7Vy3MY0MZQySi3Rw3IScxWZ9Z4oEgo1MW43YKv/XoATRUez2+vEvRG1bqS3N/8tuiKaYYc7a0HAZhA2DbUU3ALtdiqZvCTklWdS3q4ra+AIHEsqE3XocuHcFQjtaUh157MQs5cmOzy8qIkQO+QnlaT0I0njTiKGA6pJc8R7D1rWg2POEDmLb5SLXr4mFNa4XNwWwTZyIIhmOc1+3qt1N6EeOJkKNv+x9QcwWSJpRJ4qOlCC2iHEy4mJcA+wMFrvrFU7HbXAgt9GiZyO1Gu4sjcOyYOcijdkNDkAxMEG0ipg==
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io

{{- end }}
