{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgAdi84szilwE7+LB+XI667gmCxx+35u+FTYI4u2kfhTpzIB3U3ReIaZASTdJLeNqfQZBc8fPNGFjYhiyMnWAtr775FCx+Y4wThXvIyZE7T2/1+zE3KrcGVfRHMpZDEuOUBneSMigE1X2q0D0xKTzq0MmAqlGTZfBgcvfxUQFFNFg0WSjaUi52E0Y3FYFtFVZLUgsXDxJjuRZWxzWI8qZmWbKsN6WmH47/IoEg3WD9GcbuI4zy4/V2hmUbOtl+oVO2E7ephg31mGuNVDyripT2GqTR22fvhupkuHwpdIX3bKoCrO7/GmXbjnl+At0h4bHYxlbKZi/kvft/vMjKs7PD6ywKaKDns5BZgBtv8rXIzSA/5ytvfW4DKXj3tN/mnG3fxjtqM7rStYQmWvW+0XrTEvIq4R4LNOrm5XDtZNHojFHBNC97oVR7WLiCLOIc+9nUfDMMkUv69u8qYk+EB1p37nYh2/M+XralUACoKW+l8ha9NSBXVAmMrOn/y5bTxWo9sMUuhT3g9FhpaZ6/4f1uh5/BNapXAVwohWyrPMR7ouhl50S1x1HdvSPixBmQ5ZipBuHnARXoiK6fx0nt1kB/Uf4TBfBu33f1NTOZx/0qyyq+6q0/dNGjm56epKgQCFCeU1jnNvY7AzcZI/kqc9U1sEPM1wKIkSc67+l4sScLyyqKfH2IWce4NmMQ+MzJVp8IqM4qoSblsOt5wAoI4ZIbE=
    aws_secret_access_key: AgCYhSQPm91Dh2cmfi8qNe3+inrQead5esJWbHntFp3GAEVNVDmf9sXYIuLDJSr/6zpBmv0aRuoMJEn0drPzo6DSz0YA7XNwRk0jSo2r68sx3Sld9bsUMqMXtHMMwgyhOXHTAo50vTrBKEitxlOc/GOj9Jcx5rfgY6koGePQdl/SgZcEJcaMMa3MNCjkZsaDuEYo9DriBGCFYcaGGB/Z39TVIzW+akGsHU9FzFwTHVZzHiOTSIcc5pPImx5Aef3tOzq1YRKwFIcvE4j1nbrVOTJnwyVK6narwdZykKnLgVVcNKgrdKFafM4LiqcWhwhUk+lPiVhedIFV4gpO1ilHBmB0mYlejwTLnDR0Ko8mFjDGBIZ2hUVKPLY82MDQ20Z21BQGbG3ySmC40L6qxopoeu9gJ8hP2g8DTpc8LnTASN1tDSMZnJRNsbXQiyC0ZLOcEUqfeZeJQ7u/dS8YkwSqKRuZNTVB23dql+puAK0DQe9jG0JK59q3gk8L6zs8PeYxQA+25YwCUCV7n0RD9eKWyYhe8qaYrn78nuuKdTRpm4oRkl8SuJ5Z9woPUloiwH5fOHogGY93Baxz23bQoeLJ3ZT5SI8kEUVefv3T/EUDL/wtAd7VRj+ns3Kii/qWQ1tGkobG+ZfUIzxr51hVZFB7OEd608RUOllzGtpbERHqXgvviPHlNJItbMSnRQ0PiDCgkjQqgeiyrzPZUYO71SIS/2BpDSzjz8x64GEdhSjCW0I=
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
