{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-demo-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgB7sgTzviPBdHD1kGDFCwQImRRE3dpXd5GwzTu0KY8j2VLClmZhePJAzkRHxSwqJ9zufuv5g64zf5ku9CDoUoaDE4ZWHD72Cxn4Ee6RyitlEm86xPYNx+ZtBckmamI58THz5I3SUIVHIeahbqB5B0wMmT9XaEgk/v3m0tCR9PfcpqLhhR1Ni94/0tcjs34sJImW8XZCaGaIP422yyCDhLZ9eXLGIJZE4H7og4/+G2mHkhjixRJw41Ca8IDDxLd+ywTGSD0iNqsi9+fXvzLKAM10Fc8fxzG+p4oKd60nbeqUFikgQp+x5SkyKlYvg51PVSbG0Y5/zNZ+CQCWLzfzPVMRkII44ZShmEgA6scJuA7IqQtXR5ZS2/1uqupnUD3FbaZvsSJxEQHM9gnRY8fsrEytQI6vYOh1+0aiqP9Tt3F15FS2qLz+ahsy040xTgNVOQmmIJOASeBvWIMXDbAaQtwGjfcrGAiJ0IbzYfpLHwFWepLbrxHP/qrp6trMhuTFbIc+1yWahkU6CHmmBsESSlZNuUHUso0ZrhZP9waPs72hVdO1Xg6SbNAIJmSYX8M930bMOg1B7YlqxAoOVnMX0h0EefnXWpfSfmfJk6rf9h9Lr3w5Ix82mA+iM3FR1CVwG8JEhz4Y6pOG4EpScDPcIfcXHXTFMD3TZz9S5By4UDWHk0OlaKUq86gnB6aGfxn0+0tPltKk0/sWsH5u4fkuJj4Sh+FQQA==
    aws_secret_access_key: AgCA3H6/A2HHDwwismKSYnD1sWHF0bwYpKbi42yDb5R034R/4Pi0+xC+qDDi8qQaivaJPLfQsy8FB8taU66uEHOEBkzdI8FEldsjOKWsJ/bvZ5ancmgoc1RQ6CniJjcuYMCDTTc6OhTvsNk5Q6p91IAxqRm5R3XQwOQfR7fcccgfPwkcRr8GID8qwlCGOvKcqW7sp4xx8DT55ooucvmoIxlQYBrmojCv1ks5MMv9auRgJyNSGsLK7DTktvhAzCcESZRicGhGlARQcP6cq73t8Sf6SSuJwIZ5wByLxZDfAgJA+Em1UMcp2wRECH+gft8y+49eFzYM48UWwoPIWZ1fo/bCxutXAdLUJ7ByWmI6j4Ie+hVUIgebONnZ4JLjSyb17TMI5EAYgXIYkY6Ra8vmE/j5GGkDVObT1AvhdSou2JvLc5+XNSOCvNM+iVLDEBKyzheCaYU7+3393tHJ0pXlsY27qs3cg9smMmykUUDlzK8us6mS8iGVLKN/SWW5y4n4N0ix/3FLQ6+b4WzsnSHKDMkp48BL6aO8nEvtE/sFzRcHwyQYPXRiQKf2YKsmeMzu8H9MxU8vRF/nAZpVZjQln0MsrxqjeeN7JqoI1p3QE5b+VZvrpej2oT2gbTWaCTapvvBHeyOyUul6JHLpfaEXo8HONmXDL5jBnIEdTh3fRW1xuckkVcdnNyffCHbCQe2MRoLOsHR2h8QxxUAO2gQL8Umy+HeBg6DXpeFVzSg6l07mvwzM/YErf+wy
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: k10-awss3-demo-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
