{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgAMPoea+2AwE1frvjgPyxi/b42Dk5WXPQhMWSQ8RA77xdNU+j2Dd0Llg6fGLXT0obE3zYki+Q6LQaB20DkjPM3iPQShMRaC1fuc6veZmrYgi/Xr2/Gc8Oute5RUCx9bbBbjelp8iuxG1wS7dj2AdOZHwZHa7MqWoXtq9r5SejvQnhzG550www18JcqwpdzvqQfHJDR9TgqY7COW+rno6eJ22BEmZezb63a5cB5snBvd56AJ5d57qwvUAVblAB+PQD03GgeU20LMpu0VjiQLXZsArmiN9Zrv9eVwJqzTEsWEo0kxnIjGvAOq45hMerQuoF259NHDep3szEE16kr76Wes4hdmvwyXtnAV1zHuGfMh/qCFkjDoQDKN1qczTSBQdYDLikY+X2Xuq86QEQDRCFWRMDz4ufzMwujXVJHlsY54FMdgDfuHalqP3HjHHDwNNcZoyMDzTlL/QIr2niD7nx1G8s+mLdTSb4oc4plyY5/WfiHbXzLbfq6ydWn2PUOU+stsikRD19XBCs6WofRKfQNt3D/SStoGRZS3cs2ecPX45Z9oEsObXbpuaAiDP80f5g9QK1ZzjHsgrtlGHxd7cpQzPG5w1H8qVYXj1H+mPOHMg8ZqeY4GSK8T1m9zTBuX8vLo5OZGvics01WemQHSL1nMauHpzmlpH3VOupQYxU+WZ8GM8bvJPCvQthoUIvIarf7CICIwRbGrMSDPA2khYHI=
    aws_secret_access_key: AgAOxW8COmVQIpaw5/QD729ZovWtBtNFaguI+EtdgRNCPkYHJqqGeI9heki2E6BufnbZi0skDB6czuvJcYRQRyt4lXllqxjtpMs+jRw0NluND6BigJ4JPNhl3I/fLoalBdTApe+LiG7WTf9A4uIdF0mtjXAmj9vmVfksjJCN9exwqIxSGpImryp6PFfNyJrKLDdSzhC4K1spTOl/Y0MBIZJ53+bI3a58YdIdWKBjkFmj95YHPqUsVc+0UXgZmTcqNpm9x254L/ur++d+WhhtsRXp7syu3t8fv3lWTspGMjVzWEbfZHT9mIHd372hG1L07y78cjuQGRK/gRFQrtpl7+ztdkDdsZp8I7lp8jUjRHYIPLTtfRZsZG1bZmPKDxqOqpshUV3WvUoQ9ZbQQBDgAI4n4L4uLSqtkhW1gkhQfD7ISx+d8OoArXOaeXAIa99r1KW5fo5b7v9DaYFGKpsJr2aOkh8knJ4UcC8eJUe/dgCbP7l5ooE3RQpECTJ8GzOqjVmi+VW1ccgZfRhKeyOrZl3UpjG1WhjkCvxxLCR5j+7ExN3UqZQuRk4mB5Hb+DBtBMPhj22B0vMJyo5oCsZkbrneAOHpRBbWxdeJqTidXoKGcBxli5EF+ALLm3CEJdUlyEtHaqG3xRiHbCD58BYUnquGWJ/bsi26CbpKfI3gCVsR1likNOI49xPkzYUWnU5E6yRm1yzOcUttq+KROjoSA/eZA/Jmm5aefGEzTa/l2Jg=
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
