{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgAzUTfOSYmhQZudERwIKYpOtJ/Gx9nn66iB5dAZL2rxtoZdJjo4YLkQPqGEkd8kaXG/JqD8NRKVo0Tg4vpxPWdn3o66c4Ypqsq0tXeIwFEQXm7dZqWX5V+wbBXykBrQsXdcSadoOfeTVoG9M/JRB6/re5Q/gWHljnmprDqqdaEQI+okAVuZ6CEyJugCrMFctNXGRGCryPN8zUXip9of0CUPsFSskfNIPXXk9kxzrz0Gsa9tBJkKWeTGzKQPg+RzAPM5VGZU0hB4rMTC8tzANUDDOr2YETRwdYaDczuLyJw76yq5SQHWz5VOOw7ScU7UI6wMhUuMzCWskSuU5EkLnFaiBiF1oKjlmxUCh3CKX8w+NyWEXEH7KFTN/DiDlPCTb3kgu0YbRuLEUtnZ9n/EoO9+t2v1vAgI0NQTk+YXXsxoz0i/byZ54Cppa4xcJMbL8TkgqAo0UfxxGTnbBf2bm3OvK/aDki9lv7H3eHgbDeRQa0h/zD0cws/Npw2RB+UtySEMsBgexhTvNEd6vBqwzzb+MVtaVGv62B+R4cRwTHvgYzIsIhNQrVpTrNWu7w3E6WfrTX4OiwUoA6dpPWXLdOxkyQrXO0xyQMKH4HXzU6Y74ih1aKqOMApx+J+/Win4svREnObjP3goq7uJUMhtUEA/H8ifQhhhjUZNoEiGKm0j0z+i0TxPs24Zo3mqUe/+8Qs15of4WxPV4YKazWX0HfZ1K6a7qQ==
    aws_secret_access_key: AgCP0QMtFWq0e0uPwV5K4feUguttTr0aSnqT2uaD2NZW1LQGuBeg82RSWzSCuvqjlYVp8giRpwuCjBFGRDNGHgQyGuiDurZQJeIcCL7N/5mXZYQcb1dtco/WJSgD3y0FtygVgZiueiiXBMzu2XSj+0/UWouy4oIgN6LRjHt/FGOggcjtPJcxT6ElHtfOY8uBx1nMAiTI9YG92K9M9frITIvlW+CDOQo0EoPbzVOLSAR30BidvLhV26lI2utzEQf9tECXhJH+a7w9w/mD1VBQBdBWphlckDDXliazBI2/nrKGLQqpytXXh/A0xoM6Zjfpk7rglIcSaRjE7kN3a1CmIcHVEvm3A69Ft8qH9XO8WnnyHoYkOD4o7Wp2C+SaXD0aH+X/V/PrbnLeXM74PAARmuW2UA5H9FoG6rsXtFfcDLTCKLvrsNEM0SiQeBQ59ynb35rq7pAUNyqqGx+kmDacbhgzICI1VNO0nBZjQULns3KvB9+PmAaMGMkEunHKEUQf3vj/TKLC28eucGmh5B6m3t+OukpZKoZex91Rp6GpLpgmVP9HZGSBbvtoR6e6ch6n74xsIsO885dtA1TWhK0JDpiy8MAamR51Iot9P/ZBaZAeLV9XZfb0Euysgct6Z7IiCNoJi1+3YbVacm/5zhsqZhJyceninw66z3Z9s9GGzdh3YjDMavsIrxJ8QO8R0lQcvobuXGrulloASCxTgM8j5QLx+xd2zN6l2wtF3eJ06QxFsHAy4FvntFud
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io

{{- end }}
