{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgA/ZGUyOmmu3MwjRLZ65bxhisJIBMhLpT2Yp09Se8dgqJyqZipTSZVT6/nMdmOS/QRdAbU68quyyHq3AzxQjaOfDphShNzaoA0ASeTQiMZi3OeVmJluBC1Ildbr57Yki0KPiBoOQArPP3DZVneZ4jiBnJvQdWemm4Wot8ATP5qu2aIns1RxVu0986CHSJ839RW7w7isFqpU14Hnx1h62Ig8c32y452hRWY2K3D2HRTaIUjKNA3BYPiFqZxLXWU5EQvQmDLM7uznU4O//fqbC34Oz4g4QkEmw8Gq5FZuqMxS1/GCaySi9LA72d/un+onO0muywVz1nbodJPKf3dMQgk0ZBb4fAMejHB1gJvl0e6b7y2dsqqKxleD0hiSzIgdX/bhS+9JnWu3n/XUjM+gqtqih7fMcs/+zaHND5QgGpqhQ2R7JBjL5IGU9SMKIE/LlaBlnoedkIQ3HGrLm2qcW0dR1575Ihi9lWy6VZeFq33gpEcbfzFqmfb4H5FqQe+nvLLdPWzCUaVPEvEE9nZjWVhHhAFfJgZLB0LCafXrn4ZfFVIXBP/O/c6T5Xnwhb9S8YtkMgyDl6O3x7p+Z+t7GhXuo5k5fAnkFgoy+/cd+x7X7PnBURZ2TunY9Q+AKQ75m2l3F3IEBwL+/gmuv/WfFTxis7wBKJikzak/MK8In3/eAhaiHlyhK1ojYpaaarXqZMx/ZpSKqgIOSjEJsBNGom5k1ooBV1o=
    aws_secret_access_key: AgA4pa/Mq8OaeUq+MugwNzgcSpiL4jKYj7anRWavT4nNR86mgni/yfIn8jZwqB8cgarJfFfWzoLfIwYAJ0tIINBGcXf56I0lXPL0tVSt/vtE8xeSB51BxvZT5k3g0gfNABtHr9Etl8Chy72cF/Ir44VQNlCdD5XF9CR5q5qXdfeMA1hUN7CgjbhOB0FVURqB81zf9PHfBTu9VMIoXQL6AW2NlgWm0XixRmDgx5XV0isKV+P9uQC8DupWyJv6ECxeyHf4GY+xCMSNROrh3Ah9wbwpGBIJKH+EBkE1Sfh5SIzosB56mvY3S3bdct03cWgFbdGvD4ASmqmge2y3rJydVRl9B8HKX2HlEN/Mek+52WY0C0YysDIzDcZtpDVXFYfxhr6XQUicIZx0mc2YK+a+crZhOfn4Lt7i8vXN1JJIHMSXLSDoRlbzTNBx59c54sDW86bemQALZIipna+r2Nvc6mLUi3Q0QHDvhR2HXdxN7+CZZ/OQaVECtdcsERg/1X+0JxDqAGSLyH/qvR7kdioEGPmQXscQDDktQ3TWQQ0zjtTlqqL+YoZ0kCLLFu4cG/DupmAJOZ6RfQP1EBHYwzEW7HVvfHFhiE8dSL01SD2uOqYIr963tSh2i23SmZ53INL9Nbch+f4z4QqzAiAru7WaswqMgIfrDQNvUypTehXlLYMOm3KFrbCQlIq9omAC+TfCsCh+emSYT3tk8bKUZJPGkDz9CxZiLupenvLzFrO7tdCqloDSwXRkBUYbTQ==
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
