{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-webinar-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgCbhQ3x+3Yko701P4ZHsPXREIANjLWdR6VMlo77hzM+TxkZIW6G2dznenVoukmDnpMqBnJNEYJeCD6i4RkHSjrhnXvA56fLYUylwduKYqSpnbS8iakbrqAmesRpFXyxZwWxPLwTImAbsNLZUs7pRbB06Io+ZjTr3py9ePA7weUnuHGhjTTvrkgvx4q7V5UQyJbROVyH+aL1rzLmPo+C0VNOKOaqSFvHgOLK8TZaloWHx15aEO9D4F+OywFqU3mRqFY4sTNid1WPuRgU6jSt14McPdfc9VXGzJYEEkRg8oLm/G/M+lAF1lS/78N8WFl7ZO9r+MX4BelH/Oos7G1IxOPtgF3qoTOVkK4MNNgdMmq7U72D1ta28SyUKJ8BcKv0oTpXwM5rAhhT7NbhvKkdOfazMNBk0G0prZyPjp6BQed9cNlLCQGuNhWGE+11K71vVuRXj9wdKKjxshZb4AFUNn/REKQh0l/pQ35aRyzzeiBIKjBR+/2+2huoCVRBoNFAvyTwKp0dtEfSI5h8iWriGH2oO4VRnGOfeYoKx2A4bHsHZ7lVde7fp5ZVlvQdp3dDoL1HAwzEYOkquJ6E0W6eLAxrj9a8+TTCk4Vg5XRIuyXbfA3i8m8H1h4Sw+W28bizq7idgI4dYJ7lifQ68UsIeDUUYhhiNjhRSyIeYsyyEVCCJIXtRArenLiY6cHLTB9Oezq4IHcgTA8ROh5UEl5fQGDt8k6Y0A==
    aws_secret_access_key: AgAbHhPVY4TpD4SUJ1gkCCwiSF+K5LlSXXQXfpuVeOBd6m0XJD8q5P1OljuaAqzuhq0M/REXUXN5j0VrWZL9s6e+urNTGyoe7gqre6HvdonxQlpYRJ+D3HOwQJE8OBRSgoiiMTL2UWAaVf7/Jqu8hO9VuhNClnwjzzQyRtdDadzmLPwFzE/cS8zWHtEKghB/U2gEOKrWeKkxCbwokU4xV6ziDd8bw7RnetIw4gyTJ082jUba+TdDQUEyiDTpv1jkLbXVas6nzJ9Zl1TwBqwMmXenRDWN4OtStn/xDPPE7zhrPOIKwlofQQQODYH7R/eMtd/EwHRjtz+L5tPJgNw+N7osvk3xugqdFlJAq1XmBA6EMX3/L7wo8Ur6YWE8zX8HZ7fcBNPj6I5pHIo+RWl66KKqeeOqqI52ZyAfbzrO1v99s8VLh3qksYgKUL/TN7bVowTcEhn7fBs07nVDGPpYpGkGBc3AweT59W+kTsbTKLX3AJAEXXY8nqC1g65xyvXGbVOrYnVFScdtlEfQxzlalZ+d0BRMwQikdnlgashB9A41/KwxprrZV6h4kzs3EBxJlkDR1GiTmcjchwowfPdnQ0YjWrcNccQuAK1PbH7eSxDLpeZRuIfKQ1qc/CwqjuCOrqcjonbRsb1a+3RgsoZQ3hYh/3rbbnRvCi5dw9/MTqqcYRtMzxck73a9jASfAhIKL29I3GHYHpyOL0R09Y1yCWceXSZrWFCTJQD3MSFfwrHDBR4pMoMsIOKT
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: k10-awss3-webinar-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
