{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-demo-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgBNmz6Mblh4g6/Zxxto7Rh9PCzR6ykYGI8J1Fvwu0bmB1Zv103fYbuMMX+zxDHFoywf45ebTfFaMGQVaFVN097fp1TVP/a4cvkxNRtOVXiLvUnH9lrzA1DygE/WiuWKPwoKE52NkD2W2j+cbjM4d+hdqKnRFwmLOKpfDa5+CkNTx/bl4d59pkPS3DCytIBvCu70pgpSFZsR7r1sq+qgxkIn2G01b71Gok1mUnho6OW2gWQOS8npY1bsms4sCiu8jNrhMj6ziLaysTjOO1yU4Vc3EKlJMwRFOsJ/HpObRYChhy/+WHRFK6dRQJkDsDbgLyZ2jFCCfaKX/K71jSh7bI4U/8VDe15QbeL3OgDIsRoQwNg+W550QS21yKN9qmqN14SelYUVZQpNAsdLby5CdaPFh0mo/P5jvlsODZOAkNFc9voYXHPiq7t75MowLWrH594b8Ee2u298XTk255Dew5sl+nAIByWHmw2bXu06iwFjBOu00K+jRMfVAYO2+U2lSJCCojaTJrEO2nSvLIur8OHW1dSq2H9vKUgoBXntl1LRWkCRtYvhuNkPTn2uKGBoKVJhUKt1rkffQJxl+6K2f3AToEwNa8SE5x5200X8Fl1W+nsQVgRFiqnvK5SerwIs0AxbFq3hzw3B5xLYvtq2NWB++7JIzCxb+uNxc7ZSyWnsYto2i++uyeCEUdS5ZSXV7HdCUGthc4WLPOorglr8a3P/QFBItqg=
    aws_secret_access_key: AgAuwxzx7EfbFZfk+Ra+vOM23e2uUXkJ2b258IDxNzHHmC69UniIiy6WYUy/7/V/UVRpNK1BvZVXeBHp0Tgckg+uCz8kmR40XJw8g+KKitI2RgJDY5Ei+CJzMdKf7H6P6Hj4Ht47KhI/hleZ7LKWc2lCCbmHMa98IZlzycYyBjnMHlGKkWTT5ORrj/WRLT6iSYr9sHlcFY4/rnmx/9yAknUmgcOI0kjv9pNJTrJswJRjEH95Zzvh+USpkWZTfhTWqnqT5yMDC+QkfbzisSRwhhDvKZ3CaB4zCBrIXQZJMCMsuzrILFTJjX/APWzCKwhVSfHECWKpDsPtP8IAtvoxE1B+Qpzv5W/mC7qHccHfa8zbg/9BN0ifZqtoXYs7wQsVvTNoZk/8zhxoorb6L6YxeYqP4Ri9esshQ6jPLonrW0EqwJq5e/+4WA9XG1FtxGXD9OVzPocPzKhUEKiRwaM8OWtexcPJw6cGQKxIqSPLfsGD6o4zk/vZDiEhmJWXxn21O2wmEPb+Vl+9r/9thJFfIste6HH1jI//3EB6C7eqeoxcQm3/c9mvvhgSH+t8KdUs40qv9LWuDL4NJiBigsye/bblpqFh3577/M+ebkncTCfXMSkL/YYcnbGuve5ubAgzT01k9kHlMmCfXc9FDzXHXpCmc3XA8o7BIgoGSa9HXCgBkk5g0ANdAcASxOBw9EPHQnVnvt0VEddiv81RsEyhDHdY5N508q+fyHOqgYexsdGcVTJWNKwmyefTfg==
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-demo-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
