{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-demo-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgARV3eKHBBx2LKdAM6I/h9euFRMXlASKme70w1uU5SKnnBJDertkqh4U2agbE70Un4jBvJZGOwNr8mVlRfMpjxNeG4LLE70KsH7xHVyxiGtCBhy/OYAU683BnAEeUIonzKItgfYoM8lj+NX5o7A/7x0bGbqtbZbBWE6CKwhmd+eJAMSPSYSL1p7pV8JeZDDDOMxmKAKjAlDcp6T17hAflmJh10Kpdqo8DlmU0hY66fNMN3y6zBOOVhsqoeaqbXQnFDgBCuwSM1tuoUhJlIEvjqD7afKz3CTfAmsYI+Ozjy3CXoq3ER0W/lAJWuTr+BBNKA+/Wmmc2Cz0xAHb7Mi3EWcTnyIW31Ils+PIP0oUPgP1NUzb9gHThnDskjqSLjA0dliFeSHaAo9LPCZ9YCdBTswj8l0KlMWiFJ4Ky9LM5pnUTrcd3+NPwbgPYT3iQ9oolZGV4NQLu9XFM+A1TCxl2WSEUWbqSu/JM7wlL2kHQhoU2fPsVoIyHy24Qyz7gcayocaNl4F6Cwkroo4Aj7bLwGPi8WMWmmwLhqv1thmD4WJFEwrgej1rClP66Q7eIp8/ASDpemcm/gOL77qBup215XQHL8Xtc555rY7ZEcJ9xNgqE6iBcx7s+I9eOiQMYOZUgbwhUn//Bh8GshAmURnAydB6ydjwHyOL1yey/eGj1y83E4FOpJoVc4inHzzIQNPbuIuiglui+ERj9xd80jAgaTmyvckUQ==
    aws_secret_access_key: AgBsfjMEJT/ixHRVrd0qUNPRRzyei6Glg9CXrnbPSa9PslQAfJMn1SJrtaMiDNph/v90OGn9cS/LF2BEdcXh3A4lK/65loNfGgINE6gaMh9HK9ZXyq+hMCJ/pIh8omJ095OHSalv36Xj2EGD1Qta7wkTuS4WefGNMGQJs4/J2bViv96WHeXkq81vCuXHXB6twXPVVkBt0pX4nKSNnTnclGTesaVdueqHCxL75aL7uETuew206h/pr/0VQIlhAcNKwqFnrwTxUJA2AWx6xicQi5hcGmteCwC6NFenw4MqUkbO45W94VB/b5kVuGqx5JFxtEzQpmstrbNHeG5/XUrqxQVID+AqpSChuvg+OK4B5MfBeI/c/J8w3WJWVZ9Ra704gM9N++erkYdUa2qx1DxtxR/BhZP8owUtaVFNBY9FDype+GYV3hADgZjucwkXuTWSOm/ifWtyBMOe6kvkFtqqLEXKw8biH5prFS1TjlHudC6IH8VFDngPAgO1wYgHwK6QtYgz48U26pG0wiAYE51LUWQxy9QP6fFTy8HE90whMNHiSMtjjzpN6+mTVcu5P/DE4ROgmDXYiBFdI7Hdoq4vvDbXqdmoiahiGyPLzbDIYRfz5wnsRWVUasX97l6Uy/A2PEWw1v6rkNLQvsyLJfuN7HiuijY3g2Un6Rdleb+Am2YGpKiRt++c+CSy6+FIP7jBALuMu6RlhxZQQLdawyrKDZqA1w5nGlQh7w+BU6URNdVJ4U1szOC571hT
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: k10-awss3-demo-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
