{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgCGGRij1TfLtgJEye2AJyc8wUa+PNMLGZDm9yshSaW1o1krQXqXON7shT04fT1h//aPPI+xqXJXz5Z7j+t759n7zsM3ipCdBEL4V/WTZtP/lr/V0xALb93At0qIylHmvlSCOC/zcA+b0lmpBX4hkXEP/lzL4Covb/73voajQC1GvNYnznH8dZxuMBYyZrYA8PZKgoN5j37oTqMc2NJ5LPgXePYEnK9nOeKaDMxY9t3oJt24bPtAITV3IJJIZnBH8ubFHFjG0QTsa6rlgVFflM5F6n/UW3pIgIafsNJ/9PWQ/FLMZVWdqIOu+FGOfK9Au0lAXi9RWqhl4enn+X6VyuJmWjuusK3KzP2SGsWGl9dlBqFWJ1laS2IOgrxvPUrQxD86n2WEgLFHhXRwAYSS62JbF2yV7EgT7AReVuDwu8ntlgQeWnbrtbZ32bOBt22pXsFqG31JL4ZUim2eS/zvfhgMyBd0hBO35ZUXYcq5OfAQVcXLQTTu0v2yFyaZbgcrMnkUZ4Ie0d/SQFRir1uIrAn5Hudc3mSR462DcGahVUtf4WN76m5/wekZ+vhFZa93LXspYTWGELg2tu3u9rbftpE43WM9gU/GD4+tN0mLS9LDMtPMyNaYs1HheO9Gj1HNqyfijhwaFlwM9P73npa8VZEPILDT3T/01snu2Zyn6vweXBVsA9yxdxAiGthbLPRcEvPRTqs/SUuRTuYkgRAllGefZuOgKg==
    aws_secret_access_key: AgBn/+mm4SeiSwIR2i0dhPzvpJg+RQNBjy6ktEt0NjTbuwGJW/zmPQjWvQHg44C0bkRCL5x3G+lQm+qFdFfpqka6NBzEuGnhdfwGjo6iGJR2vcJHXfMb0vdQQP2U6iKzDYQDJRte3A48Osl54r0ndzS0UPjEFbHUT6KYwTWBySnUa6VrLrfvW4hyj4SKWtrYpcUjcF5CDbZytgiCwptDmn4hqWfvME7yxEa0lcs7GchHBF+EHLZiCZXH7eXY4vUKWAbsdQbBq7OOX1UW6kHT9rDAZDbpiEk6kmdkK9UwIOti0Gn37fH9wbd9N83K8ysxS/qD/xxlSxR7kc1pYZ0EARqDtK6HLlrCFSFL0ERBnd0LLKhjacCsY+D+rtDzS03VHzJqNzx4/O060y53PtIxpFdcIDfAmut7y9DQVrzyknspRXr+A8XlagWpUooUEjs0bZjB//ITkKL7jnca3gyaAvUx5po0J6D+YNfNMVFqsfhJrxqMqWSNFVbTmZCU9g3ejKNyHjqlhV7bKLmO7er1APJ630icy7bkd8T60gzhUo5AuTXI9MpJ551oUMALz9nv+hfgZmQTaAWNN0H/E+w7rjVZIhmS8Osjjx3yu333zJzxvoFAQsBmZuYe6adFiAMlH1c/oXYfoR4q1o0LaAR0iiNL2xz/OBy2V6Call0nlV44htYxg6NMSFHshnbO+hPqbzarRHD4PYbOwgu2WL8ESpPgYfNWpgKI74+rHkep/5fTXsVZJ6hpTLlF
  template:
    metadata:
      creationTimestamp: null
      name: k10-awss3-kasten-backup-secret
      namespace: kasten-io

{{- end }}
