{{- if eq .Values.kasten.enabled true }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k10-awss3-webinar-kasten-backup-secret
  namespace: kasten-io
spec:
  encryptedData:
    aws_access_key_id: AgBZlXyz+6LLYXNNibWitRsxag815sDr+UG4X4bDxHbrGRK+NB7JwmorRLt2f9WGHrDq1hvYyAI7JVsKYrbrxvwWCyH8wcxZgbIl87sFx0av+8/AqlH+QW1XqlTYpfhEpfgXRIJJA41L8Nc31f7x1te21d2X+Z1CgSYs5xZCM8NvTsG/MmvtiF9s0YfZ1fAX9+UD7i/AJIfevYVVn+KBff5jC8dZ1M+pA2N+46pLohDKSsWvUtDzLm1IjaF/4lGvElh/dzVMMKVIiTym9ni6NmYDuWxAErNJBf53roRh2VEFe/Iugdg8Mt6F6oWjGyM5a67Chd+qKI0bJ8memxzRGmj8Vzhb2JyLnogf25Jqb7pxk7IJ2CxyciwdGW7fQBgPz0ZTJvHXNDbFF+Pay3p9YVfTtJ7ViiS2G/FZm245R/ovW3XaruGO0M86ReWpydmeQzfQLPg7NR7zwmriYN8J9660ZtLxR/3EII3iNV8r6KuXuSpq8kOg16G/TIJVhjYUVklrFwfv+TZeptWTGF8S8cYyM+NF2/T9Ryc7tSnve9wWTlOs7QUDE5MkQF9GrTT8ap75XoKDWJUMr30831xfN8eqTNcYEQJBMbjCuBr/HbiAk3LvTkbrFnCK52rsDM9YsPk/0LpavWBeWhyd9TiWvmjnPvykEYoMqelEXYkNtFw3UtW2yGhTNJWFA/KOE3RymiePJAPNROFbDE+qDq2tV9Q=
    aws_secret_access_key: AgBqeMHuBoCnrqa2D+sFkg9tkC+x+Yyp+cQALbnWmRN4NGI61KXZjYQaYhbucnPTsHb8YVED9BiRYWBJh+O+eyfm7OCy5c2+hEBoTcpPW8mSwPNVE7WLdICnXGUjX2wDj4BiEQ8PXsoV4hCQjKK9TVx9Ua2Mp2Qn5fCrUIMfda91aiOsVNTSX+8wZgUWYBwdKKhEwGng6Dp4YgU32OBeGp1iOHcGsgUx56rOcSOkdXwa1h6PpdztP9iej2GMXI5sgaJ/KAHm4tTo4olRDA+2Dyi2/jVzHtdf7hMowLL0Za6Nzv2b4ihqgFJyZJpI97T7f0CsoxtcFy0mWLlr8HgOP6oFLudaAA9FcAy134Mdmy0wMGHWBoAmeh3GIqbNK0t/ye9vynixH5WBp3uPOKu1sFvW1kFfO6MI+rbe6YT7DBaLQys5HSZG5Fg+UOQG/vJex0g9l4q+b7S00W+nb1O4IU1fbrzfxqwFYfkrTjQaKJPwy3Sd7R7sFdllGcB7UHHacqL1sdViZAskBC3BRQsXXJyiapz+XNaKMXNEqdivtV2QGJNt51OgeQzSWLvQQyZPAxe1fMhrhFJO5gaEduP8qGhFwhImmD0sKmVOdLqKFTxYgIB7HGUE79V4vWxzYmFVqHllF4X+hGCFPssyR5Fx1HX/myYOmxyiBiCMAO2PQ/wRuE+5HSI2i0vLhhmdhA3SALeP4P7QjM8pX7S9+lW87n6W7wh4PeN0ULfMRAADFzU=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: k10-awss3-webinar-kasten-backup-secret
      namespace: kasten-io
    type: secrets.kanister.io/aws

{{- end }}
