apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: vm-restore
  namespace: kasten-io
spec:
  frequency: "@onDemand"
  actions:
    - action: import
      importParameters:
        profile:
          name: profile-awss3-kasten
          namespace: kasten-io
        receiveString: ""
    - action: restore
      restoreParameters: {}