apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fedora-cloudinit-secret
  namespace: vm-gitops
spec:
  encryptedData:
    userData: AgBcza3G8/6FUM9CmEVaNA1cZYTDKON2JKSduf/lGYQBZSHehlfaWzgo42KXVMosmpxK9Z0OPr+XK8knWGasr+nmKjvIPVf1FSnHlD/6iHqU5t5DtCSWKLspMfFpKqwmYu+leUT04WBtrRZZXD89iLkCWA1JDP2IeJHPgNtaavrx0c8Y/WmN1/Sdr+shoWAacP14Zolk1k9IjPVWYM9gRPs51cevgyYOHZT72MdlaCk7bGBkHbspWa30ogBj+loJ9bkwqZuqbuuNNHa9gSUU5rwu3Jdj3i1pFcVBdVJgemJQRM97LvWdsgfFLUufG/OL+31AooTiECH5CniOS/2vpBlw6RQj820hB4meqIzDFAR6Ht0uYS1uo2IkVfZV7ZXKNVF9pUp2XQfO/nFnhVdmLcwroeBEEgFwast27cgHejsnnd179Ljl6f77zlw6MGxvRZjKQ31EkuZgSBuPGy7JfzcSxhxglNhbyGIsmn6Vb9OU95dmN0RfXb91/TbavAiW6m3wWBW6sk/ju72pqh7aH5IZpXz2DUeienq9sCZfF/tmAuFi8SP3xd8Msva6lBXpnMN96l8BVIGTxpfIMlStHkLFyWINukBrLoZJbECGWnEXNBQphH5SmO6i3+rU4baFpkJQTAQlhfEwA5ViL7xaWa9INmuad/BWWpvWEVwuJKnh6UCC5yiYlIy3lDl70vsS6d9y7ssS6YYpgKl9XKvluIoR8Y3iob+pjeCIe3JHuJZ0TadzexSIZ3NGPnnl8LcjastZlEkoY4BQzDfUYZHxQQyRt6u9QQGeeg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      creationTimestamp: null
      name: fedora-cloudinit-secret
      namespace: vm-gitops

