apiVersion: v1
kind: Secret
type: secrets.kanister.io/aws             
metadata:
  name: "k10-awss3-demo-kasten-backup-secret"
  namespace: kasten-io     
data:
  aws_access_key_id: ""
  aws_secret_access_key: "" 