apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  name: sealed-secrets-certificates
  namespace: sealed-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
